force-app/main/default/objects/BotOrder__c/BotOrder__c.object-meta.xml
<CustomObject>
    <label>Bot Order</label>
    <nameField>
        <label>Order Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bot Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/BotOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Packaging</fullName>
            </value>
            <value>
                <fullName>Shipped</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Returning</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/GetOrderStatus.cls
public class GetOrderStatus {
    public class OrderOutput{ 
        @InvocableVariable(required=false) 
        public String sOrderStatus; 
    }

    public class OrderInput{ 
        @InvocableVariable(required=false) 
        public String sOrderNumber; 
    }

    @InvocableMethod(label='Get Order Status')
    public static List<OrderOutput> getUserName(List<OrderInput> orderInputs){

        Set<String> orderNumbers = new Set<String>();
        List<OrderOutput> outputs = new List<OrderOutput>();

        //Get the order numbers from the input 
        for(OrderInput orderInput: orderInputs){ 
            orderNumbers.add(orderInput.sOrderNumber); 
        }

        //Get the order objects from the set of order numbers 
        List<BotOrder__c> orders= [SELECT Name, Status__c FROM BotOrder__c WHERE Name in: orderNumbers];

       // Create a mapo for der numbers and order status values
        Map<String,String> mapNameStatus = new Map<String,String>();

        for(BotOrder__c order: orders){ 
            mapNameStatus.put(order.Name , order.Status__c); 
        }

        // Build a list of order status values for the output
        List<OrderOutput> orderOutputs = new List<OrderOutput>();

        for(OrderInput orderInput : orderInputs){
            OrderOutput orderOutput = new OrderOutput();
            //Do we have a status for this order number?
            if(mapNameStatus.containsKey(orderInput.sOrderNumber)){
                //If so, then add the status
                orderOutput.sOrderStatus = mapNameStatus.get(orderInput.sOrderNumber);
            } else{
                //If not, then add an unknow nstatus value
                orderOutput.sOrderStatus = 'Order not found';
            }
            orderOutputs.add(orderOutput);
        }

        return orderOutputs;
    }
}